//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjectApply
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntityProductEntities : DbContext
    {
        public EntityProductEntities()
            : base("name=EntityProductEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
    
        public virtual ObjectResult<string> BrandBring()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BrandBring");
        }
    
        public virtual ObjectResult<string> BrandNew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BrandNew");
        }
    
        public virtual ObjectResult<string> mark()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("mark");
        }
    
        public virtual ObjectResult<string> marks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("marks");
        }
    }
}
